import type { Metadata } from "next";
import { Inter, Josefin_Sans } from "next/font/google";
import "./globals.css";
import AuthSessionWrapper from "@/app/(context)/AuthSessionProvider";
import { PolkadotExtensionContextProvider } from "@/app/(context)/PolkadotExtensionContext";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <AuthSessionWrapper>
            <PolkadotExtensionContextProvider>
                <html lang="en">
                    <head>
                        <link rel="preconnect" href="https://fonts.googleapis.com"/>
                        <link rel="preconnect" href="https://fonts.gstatic.com"/>
                        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,opsz,wght@0,6..12,200..1000;1,6..12,200..1000&display=swap" rel="stylesheet"/>
                    </head>
                    <body className={`${inter.className} h-[100svh] relative`}>
                        <div className="gradient h-full w-full fixed">
                        </div>
                        <div className="h-full relative">
                            {children}
                        </div>
                    </body>
                </html>
            </PolkadotExtensionContextProvider>
        </AuthSessionWrapper>
    );
}
